$new_user_url = "http://#{$address}/"

$new_user_gender = "Dreng"
$new_user_child_name = "Oskar"
$new_user_child_birthday = "01-04-2004"
$new_user_child_email = "oskar7@sfkshkfs.com"
$new_user_child_phone = "12345678"
$new_user_parent_name = "Ole"
$new_user_parent_email = "ole7@sfkshkfs.com"
$new_user_parent_phone = "32165487"
$new_user_address = "Øster Voldgade 4A, 1350 København K"

# TC001
$new_user_gender_select_id = "id_child_gender"
$new_user_child_name_id = "id_child_name"
$new_user_child_birthday_id = "id_child_birthday"
$new_user_child_email_id = "id_child_email"
$new_user_child_phone_id = "id_child_phone"
$new_user_parent_name_id = "id_parent_name"
$new_user_parent_email_id = "id_parent_email"
$new_user_parent_phone_id = "id_parent_phone"
$new_user_search_address_id = "search-address"
$new_user_address_search_result_id = "ui-id-2"